# Generated by Django 4.0.3 on 2022-03-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.IntegerField(default=0)),
                ('image1', models.ImageField(blank=True, max_length=255, null=True, upload_to='products')),
                ('image2', models.ImageField(blank=True, max_length=255, null=True, upload_to='products')),
                ('image3', models.ImageField(blank=True, max_length=255, null=True, upload_to='products')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
